# Generated by Django 5.2.6 on 2025-09-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BanditModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=255)),
                ("model_weights", models.BinaryField()),
                ("hyperparams", models.JSONField(default=dict)),
                ("training_stats", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "bandit_model",
            },
        ),
        migrations.CreateModel(
            name="BanditTrainingInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.JSONField()),
                ("predicted", models.BooleanField()),
                ("actual", models.BooleanField()),
                ("reward", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bandit_training_example",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discogs_id", models.CharField(max_length=255, unique=True)),
                ("artist", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("format", models.CharField(blank=True, max_length=255)),
                ("label", models.TextField()),
                ("catno", models.CharField(blank=True, max_length=255, null=True)),
                ("wants", models.IntegerField(default=0)),
                ("haves", models.IntegerField(default=0)),
                ("added", models.DateTimeField()),
                ("genres", models.JSONField(default=list)),
                ("styles", models.JSONField(default=list)),
                ("suggested_price", models.CharField(default="", max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("wanted", models.BooleanField(default=False)),
                ("evaluated", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "discogs_discogsrecord",
                "managed": False,
            },
        ),
    ]
