# Generated by Django 5.2.1 on 2025-09-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscogsListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller_id", models.IntegerField()),
                ("record_price", models.CharField(max_length=255)),
                ("media_condition", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "discogs_discogslisting",
                "managed": False,
            },
        ),
    ]
