# Generated by Django 5.2.1 on 2025-10-08 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0004_auto_20251008_0314"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banditmodel",
            options={},
        ),
    ]
