# Generated by Django 5.2.1 on 2025-10-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0005_alter_banditmodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name='banditmodel',
            name='batch_count',
            field=models.IntegerField(default=0),
        ),
    ]
