# Generated by Django 5.2.1 on 2025-10-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0008_alter_bandittraininginstance_options"),
    ]

    operations = [
        migrations.AddField(
            model_name='bandittraininginstance',
            name='predicted_prob',
            field=models.FloatField(null=True, blank=True),
        ),
    ]
