# Generated by Django 5.2.1 on 2025-10-09 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0009_add_predicted_prob"),
    ]

    operations = [
        migrations.AddField(
            model_name="bandittraininginstance",
            name="predicted_uncertainty",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bandittraininginstance",
            name="record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bandit.record",
            ),
        ),
    ]
