# Generated by Django 5.2.1 on 2025-10-23 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0014_rename_metadata_fetched_ebaylisting_enriched"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={},
        ),
    ]
