# Generated by Django 5.2.1 on 2025-10-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0015_alter_record_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="record_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
