# Generated by Django 5.2.1 on 2025-10-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0016_record_record_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
