# Generated by Django 5.2.1 on 2025-11-11 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0022_remove_record_saved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ebaylisting",
            name="evaluated",
        ),
        migrations.RemoveField(
            model_name="ebaylisting",
            name="wanted",
        ),
    ]
