# Generated by Django 5.2.1 on 2025-11-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0024_remove_ebaylisting_enriched"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebaylisting",
            name="enriched",
            field=models.BooleanField(default=False),
        ),
    ]
