# Generated by Django 5.2.6 on 2025-12-13 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0024_remove_ebaylisting_enriched"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ebaylisting",
            old_name="saved",
            new_name="keeper",
        ),
        migrations.RemoveField(
            model_name="ebaylisting",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="ebaylisting",
            name="updated_at",
        ),
    ]
