# Generated by Django 5.2.6 on 2025-12-13 23:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0025_rename_saved_ebaylisting_keeper_and_more"),
    ]

    operations = []
