# Generated by Django 5.2.6 on 2025-12-14 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0027_alter_discogslisting_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discogslisting",
            name="seller_id",
        ),
        migrations.AddField(
            model_name="discogslisting",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bandit.record",
            ),
        ),
        migrations.AddField(
            model_name="discogslisting",
            name="seller",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
