# Generated by Django 5.2.9 on 2026-01-07 04:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0031_discogsseller"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discogsseller",
            old_name="seller",
            new_name="name",
        ),
    ]
