# Generated by Django 5.2.9 on 2026-01-07 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0032_rename_seller_discogsseller_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discogslisting",
            options={},
        ),
    ]
