# Generated by Django 5.2.9 on 2026-01-08 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0037_alter_discogslisting_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discogslisting",
            options={},
        ),
    ]
