# Generated by Django 5.2.9 on 2026-01-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0038_alter_discogslisting_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="discogslisting",
            name="currency",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="discogslisting",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
