import numpy as np
import pytest

from bandit.title_vectorizer import TitleVectorizer

titles = ["Little Johnnie / Don't Make A Fool Of Me",
 "That's Not Love / It's Not Fair",
 'Hitch It To The Horse / Cool Broadway',
 'Love (Can Make You Happy) / I Wonder (If Your Love Will Ever Belong To Me)',
 'Gonna Build A Mountain/African Waltz',
 'The Wherefore And The Why',
 'The Love We Had (Stays On My Mind) / Freedom Means',
 "Every Leaf That Falls / I'll Light A Candle",
 "C'mon And Swim",
 'Flame',
 "Man Sized Job / I'm Over You",
 "One Monkey Don't Stop No Show",
 'Baby Blue ',
 'Poverty / Run To Love',
 'Just One Step',
 'Book Of Love / You Never Loved Me',
 'Book Of Love / You Never Loved Me',
 'Let Me In',
 'Soul Dog',
 "She's The One For Me / You",
 'Hey Joe / Funny Little World',
 'A Nice Girl Like You',
 'Sidewalk Talk',
 'Funky Street / Put Our Love Together',
 'Son Of My Father',
 "Just As Long As We're In Love / I'd Rather Be With You",
 "Don't Lose Your Good Thing / You Can't Believe Everything You Hear",
 'Joy And Pain',
 "Oh Yeah, Maybe Baby / There's No Other (Like My Baby)",
 'With Your Love',
 'Help Me',
 "Lumberjack / Don't Do What I Did",
 'Tell Me How',
 'Serious',
 'Mangwane Mpulele',
 'Big Man',
 'Oh, You Beautiful Doll / Never On Sunday',
 'Missing Love',
 'Touch Me / Wild Child',
 'Girls Just Want To Have Fun',
 'Reflections In A Crystal Wind',
 "(We Kill The World) (Don't Kill The World) = (Matamos Al Mundo) No Maten Al Mundo",
 'Love Goes All The Way',
 '...But Not Forgotten',
 'Man With The World In His Hand',
 'Just For You',
 'Rammiro',
 'Image Of A Girl / 4 Steps To Love',
 'Little Girl / You',
 'Biddu Orchestra',
 'Standing At The Crossroads',
 'Crimes Of The Heart',
 'Dance My Way To Your Heart',
 'Dance With Me / Can It Be',
 "Can't Get You Out Of My Mind / What Will The Outcome Be",
 'Moonlight',
 'Ports Of The Heart',
 "Watchin' TV",
 'Slipped, Tripped, And Fell In Love / 99 Lbs.',
 'It Must Be Love / Taking My Love For Granted',
 'Take Me To The River / Could I Be Falling In Love',
 "I've Got To See You Tonight",
 "Say You Love Me / (It's Alright Now) Think I'll Make It Anyhow",
 "Workingman's Prayer / If Jesus Came To Your House",
 "Juggin' Around Part I / Juggin' Around Part II",
 'Bring It Up ',
 'Road To Ruin',
 'Come Tomorrow',
 'Kayleigh',
 'Playing God',
 'Remember Me',
 'Of Cabbages And Kings',
 "Don't Play Us Cheap",
 'Pyramid',
 'Together We Can Shine',
 'Still In The Picture',
 "She's Just A Quiet Girl (Mae) / We Three (My Echo, My Shadow And Me)",
 'Batdance',
 'Love Light In Flight',
 'If Anyone Falls',
 "It's Over",
 "Don't Walk Away",
 'Frightened Girl / Colors Of My Love',
 '(Hang On) "I\'m Coming For You"',
 'I Only Have Eyes For You',
 'Cold Hearted',
 'Lay Your Hands On Me',
 "Hangin' Tough",
 'Union Of The Snake',
 'Out Of The Blue / Foolish Beat',
 'Her And Our Baby / On A Mountain In A Mansion Stands My Love',
 'For You',
 'Get Rhythm / Hey Porter',
 'Where Would I Be Now / And The Memories "Charlie\'s Song"',
 'Miss Temptation / Wisdom Of A Fool',
 'Come See About Me ',
 'Stop! In The Name Of Love',
 "Don't Do Me Like That",
 'Land Of 1,000 Dances?!!?',
 'Together Forever',
 'Honky Tonk Man',
 'Little Sister',
 'Guitars, Cadillacs',
 "Baby's Gotten Good At Goodbye",
 'Me And Paul ',
 "You're My Best Friend / '39",
 'Percolator (Twist) / Round & Round & Round & Round',
 "Lover Please / A Lover's Question",
 "Could've Been",
 'Get Outta My Dreams, Get Into My Car',
 'My Boy-Flat Top / Seventeen',
 "Did You Ever Have To Make Up Your Mind? / Didn't Want To Have To Do It",
 'New And Different Way',
 'Son-Of-A Preacher Man',
 'Music To Stop Driving Us Crazy',
 'Strange Situation',
 '86% Of Us',
 'Flight Never Ending',
 'Eddie Money',
 "I'm A Man",
 'Jupiter 8',
 'New Horizon',
 'True Love',
 'A Little Bit Of Jazz',
 'Taking Away Your Space / Do You Wanna Boogie, Hunh?',
 'Kiss',
 'Love Changes',
 'Sophisticated Cissy / Sehorns Farms',
 'Graceland',
 'Behind These Hazel Eyes',
 'Behind These Hazel Eyes',
 'Behind These Hazel Eyes',
 'Nevada Jukebox',
 'La Bionda',
 'Loving You Again',
 'The Man With The Golden Arm (Soundtrack)',
 'Carry On',
 'Weary Blues',
 "I Can't Stand Myself (When You Touch Me) / There Was A Time",
 "Naughty Lady Of Shady Lane / Hernando's Hideaway",
 'The Dude',
 'I Believe To My Soul',
 'Faces',
 'Runaway',
 'Nasty',
 'Doc Kirby & Co',
 'See Me, Feel Me, Touch Me, Heal Me!',
 'Lab 71',
 'Your Man Is Home Tonight',
 "Ain't Nothin' Stoppin' Us Now",
 "Ain't No Backin' Up Now",
 'Trails & Passes',
 'Svalutation',
 'Pharaoh Sanders Quintet',
 'Olympiad 2001',
 'Orgonomic Music',
 'Force 5',
 'Rhythm Of Life',
 'Snap Shot',
 'Why You Wanna Treat Me So Bad?',
 'Band Of Gold / The Easiest Way To Fall',
 'Any Time, Any Place',
 'This Could Be The Night',
 "I'm The One For You",
 'Fan The Fire',
 ' Rockin To The Beat',
 'Tell It Like It Is / Why Worry',
 'Debra-Lee / A Girl I Love',
 'The Jam',
 'Street-Legal',
 'Be Yourself Tonight',
 'Harp, Voice & Tears',
 'Carry On',
 'Energy',
 'Hard As Rock',
 'Here I Am',
 'The First Cycle',
 'Ropes And Yoke-Bars',
 'Diesel Made Out Of Gold',
 'Soft Lights, Sweet Music',
 'Ice Cold',
 'Get Up And Dance',
 'American Dream',
 'Indo-Jazz Fusions',
 'Elegance',
 'Maharajah Man',
 'Live In Shalanda',
 'Inspiring',
 'Tauhid',
 'The In Sound',
 'The Melodic Stan Getz',
 'The Brothers',
 'Boss Bone',
 'The Second Adventure',
 'Cathedrals / Day By Day/My Sweet Lord',
 'Grievous Angel',
 'Psychic Magic ',
 'Sophisticated Cissy / Sehorns Farms',
 'Jam On It',
 'Lonely Girl',
 "You Be Illin'",
 'Man In The Mirror',
 'Little Thing Called Love',
 "Cold Spendin' My $ Money",
 "The Breaks / Christmas Rappin' (Part 2)",
 'Bang Your Head (Metal Health)',
 'Girls Girls Girls',
 'Only The Strong Survive / Still On The Scene',
 'Here I Go Again (USA Single Remix)',
 'I Turn To You',
 "Don't Be Stupid (You Know I Love You)",
 "Can't Cry Anymore / We Do What We Can",
 'Quit Playing Games (With My Heart)',
 "Soul Drippin'",
 'He Made A Woman Out Of Me / Nearer To You',
 "Don't Know What You Got (Till It's Gone)",
 'Love Bites',
 'No One Needs To Know',
 "Home Ain't Where His Heart Is (Anymore)",
 "Home Ain't Where His Heart Is (Anymore)",
 'The Woman In Me (Needs The Man In You)',
 'Get The Funk Out / More Than Words',
 'Cherry Pie',
 "Foolin' / Bringin' On The Heartbreak",
 'Miss Me Blind',
 'Open Arms',
 'Walk Like A Man',
 'Save Your Love',
 'She Drives Me Crazy',
 'Nobody Wants To Be Lonely',
 'Banned In The U.S.A.',
 'Precious Declaration',
 'Listen',
 'Kick Up Rumpus',
 'Manuel Goodbye',
 'Double Dutch Bus',
 "Shake Your Thang / Spinderella's Not A Fella (But A Girl DJ)",
 'Fallen Angel',
 'Edge Of A Broken Heart',
 'Power Cosmic - The Crush Of Love / Amazing Grace',
 'Fly To The Angels',
 'The Train',
 'Avant De Nous Dire Adieu',
 "Space Race / We're Gonna Make It",
 'Pretty Girls',
 'White Light/White Heat',
 'The Logical Song',
 'Sitting In Limbo / Romance And Magic',
 'Try A Little Tenderness',
 'You Mean The World To Me',
 'Another One Bites The Dust',
 'Body Language',
 'Le Spank / Monkey See, Monkey Do',
 'Ring My Bell',
 'Absolutely Right / (You And I) Butterfly',
 'The Name Of The Game',
 'Spanish Hustle',
 "Have You Seen Her / Yes I'm Ready (If I Don't Get To Go)",
 'Slow Ride',
 'Three Ring Circus',
 'The Second Time Around',
 'Go All The Way / With You In My Life',
 'Marrakesh Express / Helplessly Hoping',
 'Send Me The Pillow You Dream On ',
 'Popcorn / At The Movies',
 "Convention '72 / Funky Butt",
 'Philadelphia Freedom / I Saw Her Standing There',
 'Taxman ',
 "Sweet Talkin' Woman",
 'Without You',
 'Pour Some Sugar On Me',
 'Give Me All Your Love',
 'Gris-Gris',
 'Astro Black',
 'Bad & Beautiful',
 'Pathways To Unknown Worlds',
 'Angels And Demons At Play',
 'Lionheart',
 'The Titus Turner Story',
 'Musically Yours',
 "Mac's Mob",
 'Bronner Brothers',
 'Kickstart My Heart',
 'To Be With You / Green-Tinted Sixties Mind',
 "Cryin'",
 "Your Mama Don't Dance",
 'Easter Song',
 "We're An American Band",
 "Shinin' On",
 'Steal The Dark',
 'Tanjah',
 'Founder Of The Delta Blues',
 'Just Outside Of Town',
 'Live At The Village Vanguard',
 "Buckets O' Duckats / Shake Like T Mofo",
 'Your Thoughts My Thoughts',
 'Kalama Soul Of Zaire - Live At Salle Du Parti "Absolutely Live"',
 'The Moon And The Melodies',
 'Terra Brasilis',
 'Turbo',
 'Gerard',
 'The Whitey Album',
 'McDonald And Giles',
 'Organix',
 'Free Music One And Two',
 'The Zombies',
 "Relax, You're Soaking In It",
 'Live',
 '(GI)',
 'Only When I Lose Myself',
 'Color Me Country',
 'Alfonzo',
 'The Deirdre Wilson Tabac',
 "Blowin' The Blues Away",
 'Faith, Hope & Charity',
 'Rhythm Of Life',
 'Berserker',
 'Diasporas',
 'Mark Stewart + Maffia',
 'Curly Curve',
 'Lowrell',
 'Latitude']

def test_init_creates_unfitted_vectorizer():
    tv = TitleVectorizer()
    assert tv.fitted == False

def test_init_respects_max_features():
    tv = TitleVectorizer(max_features=200)
    assert tv.vectorizer.max_features == 200

def test_fit_sets_flag_true():
    tv = TitleVectorizer()
    tv.fit(titles)   
    assert tv.fitted == True

def test_fit_creates_vocab():
    tv = TitleVectorizer()
    tv.fit(titles)   
    assert len(tv.vectorizer.vocabulary_) > 0

def test_fit_respects_max_features_limit():
    limited_titles = titles[:50]
    tv = TitleVectorizer(max_features=50)
    tv.fit(limited_titles)
    vocab_size = len(tv.vectorizer.vocabulary_)
    assert vocab_size <= 50

def test_transform_before_fit_errors():
    tv = TitleVectorizer(titles)
    with pytest.raises(ValueError, match="FIT FIRST"):
        tv.transform("Trout Mask Replica")

def test_transform_is_numpy():
    tv = TitleVectorizer()
    tv.fit(titles)
    result = tv.transform("Trout Mask Replica")
    assert isinstance(result, np.ndarray)
    
def test_transform_batch_returns_2d_array():
    tv = TitleVectorizer()
    tv.fit(titles)
    result = tv.transform_batch(["Trout Mask Replica", "Crazy Rhythms"])
    assert isinstance(result, np.ndarray)
    assert result.ndim == 2