# Generated by Django 5.2.1 on 2025-10-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0002_discogslisting"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThresholdConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold", models.FloatField(default=0.5)),
                ("f1_score", models.FloatField(null=True)),
                ("window_size", models.IntegerField(default=500)),
            ],
            options={
                "db_table": "bandit_threshold_config",
            },
        ),
    ]
