# Generated by Django 5.2.1 on 2025-10-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0003_thresholdconfig"),
    ]

    operations = [
    migrations.AddField(
        model_name='banditmodel',
        name='batch_count',
        field=models.IntegerField(default=0),
    ),
]
