# Generated by Django 5.2.1 on 2025-10-08 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0007_batchperformance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bandittraininginstance",
            options={},
        ),
    ]
