# Generated by Django 5.2.1 on 2025-10-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0010_bandittraininginstance_predicted_uncertainty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EbayListing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ebay_id", models.CharField(max_length=255, unique=True)),
                ("ebay_title", models.TextField()),
                ("price", models.CharField(max_length=50)),
                ("currency", models.CharField(blank=True, max_length=10)),
                ("current_bid", models.CharField(max_length=50)),
                ("bid_count", models.IntegerField(default=0)),
                ("end_date", models.DateTimeField()),
                ("creation_date", models.DateTimeField()),
                ("artist", models.CharField(blank=True, max_length=255)),
                ("album", models.CharField(blank=True, max_length=255)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("format", models.CharField(blank=True, max_length=100)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("record_condition", models.CharField(blank=True, max_length=50)),
                ("sleeve_condition", models.CharField(blank=True, max_length=50)),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("style", models.CharField(blank=True, max_length=100)),
                ("saved", models.BooleanField(default=False)),
                ("metadata_fetched", models.BooleanField(default=False)),
                ("wanted", models.BooleanField(default=False)),
                ("evaluated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ebay_listings",
                "managed": False,
            },
        ),
    ]
