# Generated by Django 5.2.1 on 2025-10-11 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0011_ebaylisting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ebaylisting",
            options={},
        ),
    ]
