# Generated by Django 5.2.1 on 2025-10-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0012_alter_ebaylisting_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TfIdfDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=100, unique=True)),
                ("model_weights", models.BinaryField()),
                ("hyperparams", models.JSONField()),
                ("training_stats", models.JSONField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "similarity_index",
                "ordering": ["-created_at"],
            },
        ),
    ]
