# Generated by Django 5.2.1 on 2025-10-20 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0013_tfidfdb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ebaylisting",
            old_name="metadata_fetched",
            new_name="enriched",
        ),
    ]
