# Generated by Django 5.2.1 on 2025-10-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0018_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EbayBatchPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.IntegerField()),
                ("correct", models.IntegerField()),
                ("total", models.IntegerField()),
                ("accuracy", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ebay_batch_performance",
                "ordering": ["-batch_number"],
            },
        ),
    ]
