# Generated by Django 5.2.1 on 2025-11-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0019_ebaybatchperformance"),
    ]

    operations = [
        migrations.AddField(
            model_name="bandittraininginstance",
            name="record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bandit.record",
            ),
        ),
    ]
