# Generated by Django 5.2.1 on 2025-11-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0020_bandittraininginstance_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="saved",
            field=models.BooleanField(default=False),
        ),
    ]
