# Generated by Django 5.2.1 on 2025-11-04 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0021_record_saved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="saved",
        ),
    ]
