# Generated by Django 5.2.1 on 2025-11-23 02:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0023_remove_ebaylisting_evaluated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ebaylisting",
            name="enriched",
        ),
    ]
