# Generated by Django 5.2.6 on 2025-12-14 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0026_align_schema"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discogslisting",
            options={},
        ),
    ]
