# Generated by Django 5.2.6 on 2025-12-14 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0028_remove_discogslisting_seller_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discogslisting",
            options={"managed": False},
        ),
    ]
