# Generated by Django 5.2.9 on 2026-01-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0029_alter_discogslisting_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnapsackWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", models.FloatField(default=0.33)),
                ("price_diff", models.FloatField(default=0.33)),
                ("demand", models.FloatField(default=0.34)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
