# Generated by Django 5.2.9 on 2026-01-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0030_knapsackweights"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscogsSeller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=8)),
                ("shipping_min", models.IntegerField(blank=True)),
            ],
        ),
    ]
