# Generated by Django 5.2.9 on 2026-01-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0033_alter_discogslisting_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discogslisting",
            name="seller",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="discogsseller",
            name="shipping_min",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
