# Generated by Django 5.2.9 on 2026-01-07 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0034_alter_discogslisting_seller_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discogslisting",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="bandit.discogsseller",
            ),
        ),
    ]
