# Generated by Django 5.2.9 on 2026-01-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0035_alter_discogslisting_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discogslisting",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="bandit.record",
            ),
        ),
        migrations.AlterModelTable(
            name="discogsseller",
            table="discogs_discogsseller",
        ),
    ]
