# Generated by Django 5.2.9 on 2026-01-07 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0036_alter_discogslisting_record_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discogslisting",
            options={"managed": False},
        ),
    ]
