# Generated by Django 5.2.6 on 2026-02-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0039_discogslisting_currency_discogslisting_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnapsackSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller_name", models.CharField(max_length=255)),
                ("budget", models.FloatField()),
                ("total_cost", models.FloatField()),
                ("total_score", models.FloatField()),
                ("selected_count", models.IntegerField()),
                ("selected_items", models.JSONField()),
                ("contenders", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
