# Generated by Django 5.2.6 on 2026-02-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0040_knapsacksession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="format",
            field=models.JSONField(blank=True, max_length=255),
        ),
    ]
