# Generated by Django 5.2.6 on 2026-03-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0041_alter_record_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="api_enriched",
            field=models.BooleanField(default=False),
        ),
    ]
