# Generated by Django 5.2.6 on 2026-04-01 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0042_knapsacksession_comparison"),
        ("bandit", "0042_record_api_enriched"),
    ]

    operations = []
