# Generated by Django 5.2.6 on 2026-04-01 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0043_merge_20260401_1719"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="knapsacksession",
            table="knapsack_sessions",
        ),
    ]
