# Generated by Django 5.2.6 on 2026-04-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0044_alter_knapsacksession_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="skipped",
            field=models.BooleanField(default=False),
        ),
    ]
