# Generated by Django 5.2.6 on 2026-04-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0046_record_is_six"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="country",
            field=models.CharField(blank=True, null=True),
        ),
    ]
