# Generated by Django 5.2.6 on 2026-05-07 02:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0047_record_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="added",
        ),
        migrations.RemoveField(
            model_name="record",
            name="api_enriched",
        ),
        migrations.RemoveField(
            model_name="record",
            name="is_six",
        ),
        migrations.RemoveField(
            model_name="record",
            name="skipped",
        ),
        migrations.AlterModelTable(
            name="record",
            table="discogs_record",
        ),
    ]
