# Generated by Django 5.2.6 on 2026-05-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0048_remove_record_added_remove_record_api_enriched_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="training_set",
            field=models.BooleanField(default=False),
        ),
    ]
