# Generated by Django 5.2.6 on 2026-06-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bandit", "0049_add_training_set"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discogslisting",
            name="price",
        ),
        migrations.AlterField(
            model_name="discogslisting",
            name="record_price",
            field=models.FloatField(),
        ),
    ]
