# Generated by Django 5.2.6 on 2026-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0050_remove_discogslisting_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='training_set',
        ),
        migrations.AddField(
            model_name='record',
            name='heldout',
            field=models.BooleanField(default=False),
        ),
    ]
