# Generated by Django 5.2.6 on 2026-06-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0051_remove_record_training_set_record_heldout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='DiscogsRecord',
        ),
        migrations.RenameField(
            model_name='ebaylisting',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='ebaylisting',
            old_name='record_condition',
            new_name='media_condition',
        ),
        migrations.RenameField(
            model_name='ebaylisting',
            old_name='style',
            new_name='styles',
        ),
        migrations.RenameField(
            model_name='ebaylisting',
            old_name='album',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='discogsseller',
            name='shipping_min',
        ),
        migrations.RemoveField(
            model_name='ebaylisting',
            name='bid_count',
        ),
        migrations.RemoveField(
            model_name='ebaylisting',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='ebaylisting',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='ebaylisting',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='ebaylisting',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ebaylisting',
            name='keeper',
        ),
        migrations.RemoveField(
            model_name='ebaylisting',
            name='sleeve_condition',
        ),
        migrations.RunSQL(
            "UPDATE ebay_listings SET price = NULL WHERE price = '' OR price !~ '^[0-9]+(\\.[0-9]+)?$'",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='ebaylisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True),
        ),
    ]
