# Generated by Django 5.2.6 on 2026-07-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0052_rename_record_discogsrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayFirstPassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('model_weights', models.BinaryField()),
                ('hyperparams', models.JSONField(default=dict)),
                ('training_stats', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ebay_first_pass',
            },
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='is_auction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='wanted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='ebaylisting',
                    name='evaluated',
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[],
        ),
    ]
