# Generated by Django 5.2.6 on 2026-07-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0053_ebayfirstpassmodel_ebaylisting_evaluated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebaylisting',
            name='is_auction',
        ),
    ]
