# Generated by Django 5.2.6 on 2026-07-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0054_remove_ebaylisting_is_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaylisting',
            name='format',
            field=models.JSONField(blank=True, max_length=255),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='ebaylisting',
                    name='genres',
                    field=models.JSONField(default=list),
                ),
                migrations.AlterField(
                    model_name='ebaylisting',
                    name='styles',
                    field=models.JSONField(default=list),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE ebay_listings
                        ALTER COLUMN genres TYPE jsonb USING (
                            CASE WHEN genres IS NULL OR btrim(genres) = ''
                                THEN '[]'::jsonb
                                ELSE to_jsonb(string_to_array(genres, ', '))
                            END
                        ),
                        ALTER COLUMN genres SET DEFAULT '[]'::jsonb,
                        ALTER COLUMN styles TYPE jsonb USING (
                            CASE WHEN styles IS NULL OR btrim(styles) = ''
                                THEN '[]'::jsonb
                                ELSE to_jsonb(string_to_array(styles, ', '))
                            END
                        ),
                        ALTER COLUMN styles SET DEFAULT '[]'::jsonb;
                    """,
                    reverse_sql="""
                        ALTER TABLE ebay_listings
                        ALTER COLUMN genres TYPE text USING (
                            array_to_string(ARRAY(SELECT jsonb_array_elements_text(genres)), ', ')
                        ),
                        ALTER COLUMN genres DROP DEFAULT,
                        ALTER COLUMN styles TYPE text USING (
                            array_to_string(ARRAY(SELECT jsonb_array_elements_text(styles)), ', ')
                        ),
                        ALTER COLUMN styles DROP DEFAULT;
                    """,
                ),
            ],
        ),
    ]
