# Generated by Django 5.2.6 on 2026-07-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0055_alter_ebaylisting_format_alter_ebaylisting_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discogsrecord',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discogsrecord',
            name='master_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
