# Generated by Django 5.2.6 on 2026-07-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0056_discogsrecord_is_master_discogsrecord_master_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discogsrecord',
            name='wantlist',
            field=models.BooleanField(default=False),
        ),
    ]
