# Generated by Django 5.2.6 on 2026-07-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0057_discogsrecord_wantlist_ebaylisting_keeper_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discogsrecord',
            name='wantlist_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
