# Generated by Django 5.2.6 on 2026-08-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0058_discogsrecord_wantlist_evaluated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaylisting',
            name='keeper_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='source',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
