# Generated by Django 5.2.6 on 2026-08-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0059_ebaylisting_keeper_score_ebaylisting_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='discogslisting',
            name='discogs_listing_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='discogslisting',
            name='sleeve_condition',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
