# Generated by Django 5.2.6 on 2026-08-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0060_discogslisting_discogs_listing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discogslisting',
            name='listed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
