# Generated by Django 5.2.6 on 2026-09-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0061_discogslisting_listed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discogslisting',
            name='flat_rate_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discogslisting',
            name='flat_rate_currency',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='discogslisting',
            name='flat_rate_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discogslisting',
            name='free_shipping_min_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discogslisting',
            name='free_shipping_min_currency',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='discogslisting',
            name='free_shipping_min_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discogslisting',
            name='ships_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discogsseller',
            name='flat_rate_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discogsseller',
            name='flat_rate_currency',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='discogsseller',
            name='flat_rate_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discogsseller',
            name='free_shipping_min_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discogsseller',
            name='free_shipping_min_currency',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='discogsseller',
            name='free_shipping_min_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discogsseller',
            name='shipping_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='discogsseller',
            name='ships_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
