# Generated by Django 5.2.6 on 2026-09-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0062_discogslisting_flat_rate_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discogslisting',
            name='additional_item_rate_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discogslisting',
            name='additional_item_rate_currency',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='discogslisting',
            name='additional_item_rate_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discogsseller',
            name='additional_item_rate_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discogsseller',
            name='additional_item_rate_currency',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='discogsseller',
            name='additional_item_rate_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
