# Generated by Django 5.2.6 on 2026-09-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandit', '0063_discogslisting_additional_item_rate_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discogslisting',
            name='additional_item_rate_amount',
        ),
        migrations.RemoveField(
            model_name='discogslisting',
            name='additional_item_rate_currency',
        ),
        migrations.RemoveField(
            model_name='discogslisting',
            name='additional_item_rate_usd',
        ),
        migrations.RemoveField(
            model_name='discogsseller',
            name='additional_item_rate_amount',
        ),
        migrations.RemoveField(
            model_name='discogsseller',
            name='additional_item_rate_currency',
        ),
        migrations.RemoveField(
            model_name='discogsseller',
            name='additional_item_rate_usd',
        ),
    ]
