# Generated by Django 5.2.6 on 2026-03-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("records", models.JSONField()),
                ("predictions", models.JSONField(default=list)),
                ("mean_predictions", models.JSONField(default=list)),
                ("uncertainties", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Catalog Batch",
                "verbose_name_plural": "Catalog Batches",
                "ordering": ["created_at"],
            },
        ),
    ]
